name: Deploy Services

on:
  push:
    branches:
      - main
    paths-ignore:
        - 'infra/**'
        - '.github/workflows/deployInfrastructure.yml'
        - '.github/workflows/deployInfrastructure-workflow.yml'
  workflow_dispatch:  # Enables manual triggering
  
permissions:
  id-token: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Output Run ID
        run: echo ${{ github.run_id }}
      - name: Output Run Number
        run: echo ${{ github.run_number }}
      - name: Output Run Attempt
        run: echo ${{ github.run_attempt }}
  
  deploy-service:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      # Checkout code
      - uses: actions/checkout@main

        # Log into Azure
      - uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        
      - name: Build and deploy Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace}}/src
          dockerfilePath: WebAPI.Dockerfile
          acrName: testtodelete1234
          containerAppName: hello-world-hm
          resourceGroup: rg-dtm-jobmanager-dev