name: Deploy Infrastructure

on:
  push:
    branches:
      - main
    paths:
        - 'infra/**'
        - '.github/workflows/deployInfrastructure.yml'
        - '.github/workflows/deployInfrastructure-workflow.yml'
  workflow_dispatch:  # Enables manual triggering
    inputs:
      create_management_resource_group:
        description: 'Create a management resource group'
        required: false
        default: true
        type: boolean
  
permissions:
  id-token: write
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Output Run ID
        run: echo ${{ github.run_id }}
      - name: Output Run Number
        run: echo ${{ github.run_number }}
      - name: Output Run Attempt
        run: echo ${{ github.run_attempt }}
  
  deploy-dev:
    name: Deploy Infrastructure
    uses: ./.github/workflows/deployInfrastructure-workflow.yml
    with:
      environment: dev
    secrets: inherit

  deploy-test:
    name: Deploy Infrastructure
    needs: deploy-dev
    uses: ./.github/workflows/deployInfrastructure-workflow.yml
    with:
      environment: test
    secrets: inherit

  deploy-prod:
    name: Deploy Infrastructure
    needs: deploy-test
    uses: ./.github/workflows/deployInfrastructure-workflow.yml
    with:
      environment: prod
    secrets: inherit