name: Deploy Infrastructure

on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        type: string
      create_management_resource_group:
        description: 'Create the management resource group'
        required: true
        default: true
        type: boolean

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    name: ${{ inputs.environment }}
    steps:
        # Checkout code
      - uses: actions/checkout@main

        # Log into Azure
      - uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

        # Copy infra specific 'main.<env>.parameters.json' to 'main.final.parameters.json'
      - name: Add environment specific variables to main.final.parameters.json
        run: |
          touch ./infra/main.final.parameters.json
          cat ./infra/main.${{ inputs.environment }}.parameters.json >> ./infra/main.final.parameters.json

        # Deploy infrastructure using Bicep and 'main.final.parameters.json' created above
      - name: Deploy / ${{ inputs.environment }}
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          scope: subscription
          template: ./infra/main.bicep
          region: WestUS
          parameters: ./infra/main.final.parameters.json
          additionalArguments: '--parameters createManagementResourceGroup=${{ inputs.create_management_resource_group }}'
          failOnStdErr: false