name: Deploy Infrastructure

on:
  push:
    branches:
      - main 
  workflow_dispatch:  # Enables manual triggering
    inputs:
      create_management_resource_group:
        description: 'Create a management resource group'
        required: true
        default: true
        type: boolean
  
permissions:
  id-token: write
  contents: read
jobs:
  deploy-dev:
    name: Deploy Infrastructure
    uses: ./.github/workflows/deployInfrastructure-workflow.yml
    with:
      environment: dev
      create_management_resource_group: ${{ inputs.create_management_resource_group }}
    secrets: inherit

  deploy-test:
    name: Deploy Infrastructure
    needs: deploy-dev
    uses: ./.github/workflows/deployInfrastructure-workflow.yml
    with:
      environment: test
    secrets: inherit

  deploy-prod:
    name: Deploy Infrastructure
    needs: deploy-test
    uses: ./.github/workflows/deployInfrastructure-workflow.yml
    with:
      environment: prod
    secrets: inherit